### ISSUE TITLE
Remove old Shader Loader

### ISSUE THREAD

**Issue by GER-Space** [HaArLiNsH/TextureReplacerReplaced#15]
ce can remove the old shader load logic and convert the TRVisor shader into an KSP asset bundle. (which will be loaded with the reflective shader)
I also sorted out the issues with the OpenGL target, so all shaders will work under MacOS and Linux.

**Comment by HaArLiNsH** [comment]
sounds good :)

**Comment by GER-Space** [comment]
I'll make a new PullRequest as soon #6 is merged. This will make the review easier.

**Comment by GER-Space** [comment]
ok this can be closed
