### ISSUE TITLE
MM compatibility

### ISSUE THREAD

**Issue by Sigma88** [HaArLiNsH/TextureReplacerReplaced#2]
with #1 I've added MM compatibility,

for now it's just as simple as telling TR to wait untill MM has edited the nodes and THEN load the nodes.

before TR was loading the nodes before MM had time to edit them.

Even if this is good enough for now, I always wanted a way to edit single textures.

what I proposed way back a lot of time ago, and nobody cared, was to add an extra layer to target specific textures.

something that would look like this:

```
TextureReplacer
{
    ReplaceByName
    {
        Texture
        {
            name = logoFullRed_alt
            texture = MyMod/Textures/newTexture
        }
    }
}
```

this will allow people to target specific textures and could be used as a way to add compatibility between multiple texture packs that may overlap for some (but not all) the textures

---

if you like the idea I think I can look into if it's possible to do that

**Comment by HaArLiNsH** [comment]
Well I'm tempted to say that I like the idea. I'm new in the dev side of MM, so if you can find an effective way to do it that others can also use for their mod, lets try to do it.

**Comment by HaArLiNsH** [comment]
I've merged your PR with the Master branch, lets see how it goes :)
