### ISSUE TITLE
reflections

### ISSUE THREAD

**Issue by Sigma88** [HaArLiNsH/TextureReplacerReplaced#49]
Since I'm only interested in reflections I would like to have a standalone plugin that only provides that feature.

I'm willing to compile it myself if you don't want to bother, but I'm getting lost in the code, could you point out which are the minimum requirements for the reflections to work so I can isolate only those bits of code?

thanks

**Comment by HaArLiNsH** [comment]
This could be a good idea, even if I don't really see why you would want to "loose " time on this as you can have a nearly vanilla experience with TRR.  Let me some days to finish the next release/bugfixing and we can look at this. 
The first problem I see, is that we still have issues with the relfection shader (the one we have now seems to don't work on Linux) and we have also some problem with the animations (when the reflections script update, it shows the idle face for a frame. )
