### ISSUE TITLE
Add reflective shader

### ISSUE THREAD

**Issue by GER-Space** [HaArLiNsH/TextureReplacerReplaced#6]
this is the Issue for the pullrequest I'll send.

You can find some documentation about the shader loader here:

[http://forum.kerbalspaceprogram.com/index.php?/topic/161837-tutorial-how-to-load-and-use-custom-shaders-within-ksp/](http://forum.kerbalspaceprogram.com/index.php?/topic/161837-tutorial-how-to-load-and-use-custom-shaders-within-ksp/)

I also changed the startup time from instant to Mainmenue, because I see no reason for such an early start, as no asset bundles are loaded (and no shaders are available) and modulemanager is still working.

**Comment by HaArLiNsH** [comment]
Do we need to have the 2 others files (DirectX.bundle and OpenGL.bundle) with the one you provided ? 
Because reflections on the helmet don't seems to work without them. 
It cause a big load, near to a freeze, just after the loading screen and before the main menu. 

I made a branch to work on this one : dev_reflective

**Comment by GER-Space** [comment]
The bundle files contain the visor shader, so yes they are still required. 
They are also loaded via the legacy shader loader, which can be removed as soon I find a way to compile all shaders with directx and opengl support.
About the merging errors with the module manager branche: I thing large parts of the branch is not required as soon you change the startup type to from instantly to mainmenu, because this is the tine when mm has been finished its stuff.
I ll hope I find tomorrow some time to look into this and provide a merged version.

**Comment by HaArLiNsH** [comment]
I think I messed up a bit my branches :)
I merged dev3states (witch contain MM & my work)  to master then reverted when I saw your PR with the conflict and now its a little mess. Hopefully, Master is back as it was for the last release. I'm still a noob in this system. :) 
I was editing my previous response while I was working. Glad you saw the conflict 
I set up a clone of the master called **3states+ MM + reflection** and it contains the things from dev_3states(so the 3states&MM). Can you look from this one ?

**Comment by GER-Space** [comment]
you should merge your changes, I'll sort it out and send a new PR.

**Comment by HaArLiNsH** [comment]
alright :)

**Comment by HaArLiNsH** [comment]
done !

**Comment by GER-Space** [comment]
OK, I'll merge my changes sometime this weekend. It will take some time, as I will make some bigger changes how the mod is initialized.

**Comment by HaArLiNsH** [comment]
This looks nice, I'll merge this immediately so you can continue.

**Comment by HaArLiNsH** [comment]
Do you think it could be possible to add an NRM on the visor and keep the reflection ?

**Comment by GER-Space** [comment]
What is an NRM?

**Comment by GER-Space** [comment]
Normal map support? this would be possible.

**Comment by HaArLiNsH** [comment]
yeah NRM stands for the Normal Map :) 
This could lead to great and funky visors.  My first aim was to make a different visor for the level 5 (so I'll need to make level for them too but that's the easy part)

**Comment by GER-Space** [comment]
this can be closed
